### ISSUE TITLE
Attribute Error in PSISIM HISPEC Tutorial.ipynb 

### ISSUE THREAD

**Issue by NYRIAstronomy** [planetarysystemsimager/psisim#31]
I get an attribute error towards the end of the tutorial script "PSISIM HISPEC Tutorial.ipynb "
I am using Python 3.8.5. 
(This is Saavidra Perera, I accidentally issued this from the wrong github account)

![Screenshot 2021-05-06 at 12 17 14 PM](https://user-images.githubusercontent.com/47816759/117878639-ca8d7100-b25a-11eb-8d4f-563edc6f9a20.png)

**Comment by maxwellmb** [comment]
I get the same error. 

@danechever to me it looks like this is because of how the previous cell splits things out, but without propagating the astropy units.

**Comment by maxwellmb** [comment]
I fixed all this issue by making sure the full astropy Quantity was being passed, not just the *.value
